#include "model/SdkCatalog.cpp"
#include "model/CaptureIdRegistry.cpp"
#include "model/GeometryStatusProjector.cpp"
#include "engine/CaptureOutcome.cpp"
#include "model/CaptureEvidenceSummary.cpp"
#include "platform/WindowsPathCodec.cpp"
#include "platform/WindowsDirectoryAlias.cpp"
